if __name__ == "__main__":

    szo = input("Szó: ")

    szo1 = szo.replace("A", "a")
    szo2 = szo1.replace("Á", "á")
    szo3 = szo2.replace("B", "b")
    szo4 = szo3.replace("C", "c")
    szo5 = szo4.replace("D", "d")
    szo6 = szo5.replace("E", "e")
    szo7 = szo6.replace("É", "é")
    szo8 = szo7.replace("F", "f")
    szo9 = szo8.replace("G", "g")
    szo10 = szo9.replace("H", "h")
    szo11 = szo10.replace("I", "i")
    szo12 = szo11.replace("Í", "í")
    szo13 = szo12.replace("J", "j")
    szo14 = szo13.replace("K", "k")
    szo15 = szo14.replace("L", "l")
    szo16 = szo15.replace("M", "m")
    szo17 = szo16.replace("N", "n")
    szo18 = szo17.replace("O", "o")
    szo19 = szo18.replace("Ó", "ó")
    szo20 = szo19.replace("Ö", "ö")
    szo21 = szo20.replace("Ő", "ő")
    szo22 = szo21.replace("P", "p")
    szo23 = szo22.replace("Q", "q")
    szo24 = szo23.replace("R", "r")
    szo25 = szo24.replace("S", "s")
    szo26 = szo25.replace("T", "t")
    szo27 = szo26.replace("U", "u")
    szo28 = szo27.replace("Ú", "ú")
    szo29 = szo28.replace("Ü", "ü")
    szo30 = szo29.replace("Ű", "ű")
    szo31 = szo30.replace("V", "v")
    szo32 = szo31.replace("W", "w")
    szo33 = szo32.replace("X", "x")
    szo34 = szo33.replace("Y", "y")
    szo35 = szo34.replace("Z", "z")
    szo36 = szo35.replace(".", "")
    szo37 = szo36.replace("?", "")
    szo38 = szo37.replace("!", "")
    szo39 = szo38.replace(",", "")
    szo40 = szo39.replace("-", "")
    szo41 = szo40.replace(":", "")
    szo42 = szo41.replace(" ", "")

    szo43 = szo41[::-1]
    szo44 = szo43.replace("sc", "cs")
    szo45 = szo44.replace("zd", "dz")
    szo46 = szo45.replace("szd", "dzs")
    szo47 = szo46.replace("yg", "gy")
    szo48 = szo47.replace("yl", "ly")
    szo49 = szo48.replace("yn", "ny")
    szo50 = szo49.replace("zs", "sz")
    szo51 = szo50.replace("yt", "ty")
    szo52 = szo51.replace(" ", "")

    if szo42 == szo52:
        print("Palindróm")
    else:
        print("Nem palindróm")

